config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  devise_for :users

  resources :tweets do
    post 'like' => 'likes#create'
    delete 'like' => 'likes#destroy'
  end
    
  resources :users, only: [:show] do
    get 'likes' => 'likes#index'
  end

  get 'likes/create'

  get 'likes/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, {presence: true}
  has_many :likes, :dependent => :destroy
  has_many :liked_users, :through => :likes, :source => :user

  def like(user_id)
    self.likes.create(user_id: user_id)
  end

  def unlike(user_id)
    self.likes.where(user_id: user_id).destroy_all
  end

  def liked?(user_id)
    self.likes.exists?(user_id: user_id)
  end

  def liked_count
    likes.size
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, {presence: true, uniqueness: true, length: {maximum: 20}}
  has_many :tweets 
  has_many :likes
  has_many :liked_tweets, :through => :likes, :source => :tweet
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def liked_count
    likes.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @tweets = @user.liked_tweets.order(created_at: :desc)

    render "users/show"
  end

  def create
    if(user_signed_in?)
      tweet = Tweet.find(params[:tweet_id])
      if tweet.liked?(current_user.id) == false
        tweet.like(current_user.id)
      end

      redirect_back(fallback_location: root_path)
    else
      redirect_to "/users/sign_in"
    end
  end

  def destroy
    if(user_signed_in?)
      tweet = Tweet.find(params[:tweet_id])
      tweet.unlike(current_user.id)

      redirect_back(fallback_location: root_path)
    else
      redirect_to "/users/sign_in"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to tweets_path if user_signed_in?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweet = Tweet.new
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def create
    if(user_signed_in?)
      @tweet = current_user.tweets.build(tweet_params)
      @tweet.save
      redirect_to tweets_path
    else
      redirect_to "/users/sign_in"
    end
  end

  def destroy
    if(user_signed_in?)
      @tweet = Tweet.find(params[:id])
      @tweet.destroy
      redirect_to tweets_path
    else
      redirect_to "/users/sign_in"
    end
  end

  private
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_topnav.html.erb
<nav class="navbar has-shadow">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to "TEAM-Z", root_url, class: "navbar-item is-size-4 has-text-weight-bold" %>
      <%= link_to "タイムライン", tweets_path, class: "navbar-item" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item is-right is-hidden-desktop" %>
    </div>

    <div class="navbar-end">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item is-hidden-touch" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Micropost</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <link href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>  
  </head>

  <body>
    <%= render "layouts/topnav" if user_signed_in? %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/static_pages/home.html.erb
<section class="hero is-fullheight is-primary is-bold">
  <div class="hero-head">
    <header class="navbar is-shadowless">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "TEAM-Z", root_url, class: "navbar-item is-size-4 has-text-weight-bold" %>
          <%= link_to "ログイン", new_user_session_path, class: "navbar-item is-right is-hidden-desktop" %>
        </div>
        <div class="navbar-end">
          <%= link_to "ログイン", new_user_session_path, class: "navbar-item is-hidden-touch" %>
        </div>
      </div>
    </header>
  </div>

  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-2">新卒開発研修2020</h1>
      <%= link_to "ユーザー登録", new_user_registration_path, class: "button is-primary is-inverted is-large" %>
    </div>
  </div>
</section>

app/views/tweets/_form.html.erb
<div class="tweet-form">
  <%= form_for(tweet) do |f| %>
    <div class="field">
      <p class="control">
        <%= f.text_area :content, placeholder: "いまどうしてる？(140文字以内)", class: "textarea", maxlength:140 %>
      </p>
    </div>

    <nav class="level">
      <div class="level-left"></div>
      <div class="level-right">
        <p class="control">
          <%= f.submit "ツイート", class: "button is-primary" %>
        </p>
      </div>
    </nav>
  <% end %>
</div>

app/views/tweets/_tweet_list.html.erb
<ul class="tweet-list">
  <% tweets.each do |tweet| %>
    <li>
      <p>
        <strong><%= link_to "@#{tweet.user.username}", user_path(tweet.user) %></strong>
        <small>
          <%= tweet.created_at.strftime("%-m/%-d %H:%M") %>
          <% if tweet.user_id == current_user.id %>
            <%= link_to "削除", tweet_path(tweet), data: {:confirm => "ツイートを削除しますか？"}, method: :delete %>
          <% end %>
        </small>
      </p>
      <%= simple_format h(tweet.content) %>
      <p class="tweet-action-bar">
        <% if tweet.liked?(current_user.id) %>
          <%= link_to tweet_like_path(tweet), method: :delete do %>
            <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to tweet_like_path(tweet), method: :post do %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>
        <span><%= tweet.liked_count %></span>
      </p>
    </li>
  <% end %>
</ul>

app/views/tweets/index.html.erb
<% if user_signed_in? %>
  <div class="container">
    <section class="section">
      <div class="columns">
        <div class="column is-4">
          <%= render "users/profile", user: current_user %>
        </div>

        <div class="column is-8">
          <%= render "form", tweet: @tweet %>
          <%= render "tweet_list", tweets: @tweets %>
        </div>
      </div>
    </section> 
  </div>
<% else %>
    <p> ログアウト状態です。</p>
    <%= link_to "ログインしてください", "/users/sign_in" %>
<% end %>

app/views/users/_profile.html.erb
<div class="profile">
  <p class="is-size-5 has-text-weight-bold">@<%= user.username %></p>
  <p class="has-text-grey"><%= "#{user.created_at.strftime('%Y年%-m月')}に登録" %></p>

  <nav class="level is-mobile profile-counter">
    <div class="level-left">
      <div class="level-item">
        <div>
          <p class="is-size-7 has-text-weight-bold">ツイート</p>
          <%= link_to user.tweets.size, user_path(user), class: "is-size-5" %>
        </div>
      </div>
      <div class="level-item">
        <div>
          <p class="is-size-7 has-text-weight-bold">いいね</p>
          <%= link_to user.liked_count, user_likes_path(user), class: "is-size-5" %>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <section class="section">
    <div class="columns">
      <div class="column is-4">
        <%= render "users/profile", user: @user %>
      </div>
      
      <div class="column is-8">
        <%= render "tweets/tweet_list", tweets: @tweets %>
      </div>
    </div>
  </section>
</div>